#spring:
#  datasource:
#    url: jdbc:mysql://172.18.0.1:3306/berry?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
#    username: berry
#    password: Berry123
#    driverClassName: com.mysql.jdbc.Driver 
#  cloud: 
#    stream:
#      kafka:
#        binder:
#          zkNodes: 172.18.0.1
#          brokers: 172.18.0.1     
#  
#event:
#  enable: true  
#  
#logging:
#  file: logs/berry-boot.log
#
#berry:
#  import_path: "/tools/upload/berry/"
 